### ISSUE TITLE
Training Error: launcher() got an unexpected keyword argument 'viewer_cfg'

### ISSUE THREAD

**Issue by charisoudis** [zju3dv/4K4D#36]
Hi, and thanks for sharing the code of this awesome work!

I am trying to train 4K4D on proprietary 12-view data. After successfully initializing vhulls and surfs, I am trying to run the suggested training command:
```evc-train -c configs/exps/4k4d/4k4d_athlone_c12p1.yaml```

and get stuck at the following error:
```TypeError: launcher() got an unexpected keyword argument 'viewer_cfg'```

Could you please guide me debugging or resolving this?

------------------------------------------------------------------------------------------

The complete logs are:
```bash
17:10:37 Starting experiment: base, command: train                                                                                  main.py:84
17:14:40 Preparing vhulls /data/nas/General/AthloneCapture/12camera/img_p1c/vhulls TRAIN 100% ━━━━━━━━ 1,590/1… 0:04:01 < 0:00:00 6.928     v…
                                                                                                                                  it/s        
17:14:… Loading mask bytes for /data/nas/General/AthloneCapture/12camera/img_p1c/masks TRAIN 100% ━━━━━━━ 17,490… 0:00:17 < 0:00:00 984.5   p…
                                                                                                                                    it/s      
17:18:… Loading imgs bytes for /data/nas/General/AthloneCapture/12camera/img_p1c/images TRAIN 100% ━━━━━━━ 17,490… 0:03:21 < 0:00:00 83.47  p…
                                                                                                                                     it/s     
17:19:39 Cropping msks imgs for /data/nas/General/AthloneCapture/12camera/img_p1c TRAIN 100% ━━━━━━━━━ 17,490/… 0:01:18 < 0:00:00 231.5     p…
                                                                                                                                  it/s        
17:19:42 Preparing vhulls /data/nas/General/AthloneCapture/12camera/img_p1c/vhulls VAL 100% ━━━━━━━━━━━ 16/16  0:00:02 < 0:00:00 7.427 it/s v…
17:19:43 Loading mask bytes for /data/nas/General/AthloneCapture/12camera/img_p1c/masks VAL 100% ━━━━━━━ 176/176  0:00:00 < 0:00:00 1,319   p…
                                                                                                                                    it/s      
17:19:… Loading imgs bytes for /data/nas/General/AthloneCapture/12camera/img_p1c/images VAL 100% ━━━━━━━ 176/176  0:00:02 < 0:00:00 94.33   p…
                                                                                                                                    it/s      
17:19:45 Cropping msks imgs for /data/nas/General/AthloneCapture/12camera/img_p1c VAL 100% ━━━━━━━━━━ 176/176  0:00:00 < 0:00:00 301.4 it/s p…
17:21:06 Loading init pcds from /data/nas/General/AthloneCapture/12camera/img_p1c/surfs 100% ━━━━━━━━━ 1,590/1… 0:01:19 < 0:00:00 16.09     p…
                                                                                                                                  it/s        
17:21:07 Visualization output: data/result/base/{RENDER,DEPTH,ALPHA}                                         volumetric_video_visualizer.py:80
         Saved config file to data/record/base/base_1716139267.yaml                                                           recorders.py:105
         Starting learning rate config: {'lr': 0.005, 'eps': 1e-15, 'weight_decay': 0.0}                                      optimizers.py:48
         Special learning rate config: {'lr': {'pcds': 1e-05, 'resd_regressor': 0.0005, 'geo_regressor': 0.0005}}             optimizers.py:54
17:21:08 Number of optimizable parameters: 1258741734 (1258.74 M)                                                                  main.py:264
         Runtime exception: launcher() got an unexpected keyword argument 'viewer_cfg'                                    console_utils.py:393
╭──────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────╮
│ /4K4D/easyvolcap/utils/console_utils.py:390 in inner                                                                                       │
│                                                                                                                                            │
│ ❱ 390 │   │   │   │   return func(*args, **kwargs)                                                                                         │
│                                                                                                                                            │
│ /mnt/c/Users/Athanasios/PycharmProjects/humanrf/src/ants/fourkfourd/easyvolcap/scripts/main.py:280 in main                                 │
│                                                                                                                                            │
│ ❱ 280 │   │   globals()[args.type](cfg)  # invoke this (call callable_from_cfg -> call_from_cfg)                                           │
│                                                                                                                                            │
│ /4K4D/easyvolcap/engine/registry.py:56 in inner                                                                                            │
│                                                                                                                                            │
│ ❱  56 │   │   return call_from_cfg(func, cfg)                                                                                              │
│                                                                                                                                            │
│ /4K4D/easyvolcap/engine/registry.py:47 in call_from_cfg                                                                                    │
│                                                                                                                                            │
│ ❱  47 │   return func(**call_args)                                                                                                         │
│                                                                                                                                            │
│ /mnt/c/Users/Athanasios/PycharmProjects/humanrf/src/ants/fourkfourd/easyvolcap/scripts/main.py:272 in train                                │
│                                                                                                                                            │
│ ❱ 272 │   launcher(**kwargs, runner_function=runner.train, runner_object=runner)                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: launcher() got an unexpected keyword argument 'viewer_cfg'
*** launcher() got an unexpected keyword argument 'viewer_cfg'
> /mnt/c/Users/Athanasios/PycharmProjects/humanrf/src/ants/fourkfourd/easyvolcap/scripts/main.py(272)train()
    270
    271     # The actual calling, with grace full exit
--> 272     launcher(**kwargs, runner_function=runner.train, runner_object=runner)
    273
    274
```

My main config file, `4k4d_athlone_c12p1.yaml` is:
```yaml
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/r4dv.yaml # network model configuration
    - configs/datasets/athlone/c12p1_obj.yaml # dataset usage configuration
    - configs/specs/mask.yaml # specific usage configuration
 ```

while the dataset config after vhull processing is, `configs/datasets/athlone/c12p1_obj.yaml` is:
```yaml
# 12 Cam - 1 Person
configs: configs/datasets/athlone/c12p1.yaml

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg
        data_root: /data/nas/General/AthloneCapture/12camera/img_p1c
        vhull_thresh: 0.95
        count_thresh: 12 # how many views are needed for marking reprojection as valid
        bounds: [[-0.7680, -0.4098, -0.5342], [ 1.4570, 0.5302, 1.1758]]  # !: BATCH

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
```

the parent dataset config, `configs/datasets/athlone/athlone.yaml`:
```yaml
dataloader_cfg:
    dataset_cfg: &dataset_cfg
        bounds: [[-5.0, -5.0, -5.0], [5.0, 5.0, 5.0]]
        use_aligned_cameras: False
        force_sparse_view: True
        view_sample: [0, 11, 1] # how many views there are
        frame_sample: [0, null, 1] # how many frames there are
        ims_pattern: "{frame:04d}.jpg"

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        frame_sample: [0, null, 100]
        ims_pattern: "{frame:04d}.jpg"
    sampler_cfg:
        view_sample: [0, 11, 3]

model_cfg:
    sampler_cfg:
        surface_radius: 0.05

viewer_cfg:
    # init_camera_index: 10
    camera_cfg:
        world_up: [0, 1, 0]
        # prettier-ignore
        R: [[0.9982823133468628, -0.0, 0.05858706682920456], [-0.008179787546396255, -0.9902100563049316, 0.13937781751155853], [0.05801350250840187, -0.13961763679981232, -0.9885091781616211]]
        # prettier-ignore
        T: [[-0.02317585051059723], [1.3044800758361816], [1.235785961151123]]
        # prettier-ignore
        K: [[1566.0,0.0,683.0],[0.0,1566.0,384.0],[0.0,0.0,1.0]]
```
