### ISSUE TITLE
ENeRF-Outdoor rendering with pretrained model is worse than demo video

### ISSUE THREAD

**Issue by hitsx** [zju3dv/4K4D#70]
I have set up the environment, download the pretrained model and ENeRF Outdoor full dataset. I launch the command:

`evc-gui -c configs/projects/realtime4dv/rendering/4k4d_actor1_4.yaml,configs/specs/video.yaml,configs/flex.yaml
`

this is the content of flex.yaml:
```
configs: configs/specs/fp16.yaml

model_cfg:
    sampler_cfg:
        render_gs: True

val_dataloader_cfg:
    dataset_cfg:
#        ratio: 0.5
        frame_sample: [100, 110, 1]
        cache_raw: False

model_cfg:
    sampler_cfg:
        cache_size: 50
```

And what I get is like this, if I change the point of view, there will be many artifacts.
![Image](https://github.com/user-attachments/assets/700e1855-cd08-4291-843d-563e1d2398e0)

Which is worse than the demo video:
![Image](https://github.com/user-attachments/assets/7aab7b3f-f9e9-46d4-8461-8717b1fb566e)

Can anybody can help me to check where is the problem?
